_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139689749172720
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 8954
  id:
    block:
      block_dir: blocks/139690382585808
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 8954
dtype: !!python/name:meerkat.block.manager.BlockManager ''
