_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139690005976688
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 9021
  id:
    block:
      block_dir: blocks/139690006317664
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 9021
dtype: !!python/name:meerkat.block.manager.BlockManager ''
