_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139708440587280
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 9190
  id:
    block:
      block_dir: blocks/139708912694416
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 9190
dtype: !!python/name:meerkat.block.manager.BlockManager ''
