_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/139924294514960
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 6020
  slices:
    block:
      block_dir: blocks/139925082081072
      block_index:
        start: 0
        step: null
        stop: 1
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 6020
dtype: !!python/name:meerkat.block.manager.BlockManager ''
