_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/140493269596624
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 8989
  id:
    block:
      block_dir: blocks/140493269593056
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 8989
dtype: !!python/name:meerkat.block.manager.BlockManager ''
