original_instances_config:
  dir: original_instances
  instances:
    p_72776: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_72793: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_72799: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_118660: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_120032: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_121123: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_121880: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_122144: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_122493: 
      pattern_size: 10
      knn_num: 5
      snr: -1
    p_122653: 
      pattern_size: 10
      knn_num: 5
      snr: -1

low_noise_instances_config:
  dir: "low_noise_instances"
  instances:
    p_72776: 
      pattern_size: 10
      knn_num: 5
      snr: 4 
    p_72793: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_72799: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_118660: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_120032: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_121123: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_121880: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_122144: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_122493: 
      pattern_size: 10
      knn_num: 5
      snr: 4
    p_122653: 
      pattern_size: 10
      knn_num: 5
      snr: 4

medium_noise_instances_config:
  dir: "medium_noise_instances"
  instances:
    p_72776: 
      pattern_size: 10
      knn_num: 5
      snr: 1 
    p_72793: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_72799: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_118660: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_120032: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_121123: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_121880: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_122144: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_122493: 
      pattern_size: 10
      knn_num: 5
      snr: 1
    p_122653: 
      pattern_size: 10
      knn_num: 5
      snr: 1

high_noise_instances_config:
  dir: "high_noise_instances"
  instances:
    p_72776: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25 
    p_72793: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_72799: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_118660: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_120032: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_121123: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_121880: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_122144: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_122493: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25
    p_122653: 
      pattern_size: 10
      knn_num: 5
      snr: 0.25