_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/139689756182128
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 6103
  slices:
    block:
      block_dir: blocks/139689765598688
      block_index:
        start: 0
        step: null
        stop: 3
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 6103
dtype: !!python/name:meerkat.block.manager.BlockManager ''
