_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/140037333886528
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 5988
  slices:
    block:
      block_dir: blocks/140037329133920
      block_index:
        start: 0
        step: null
        stop: 3
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 5988
dtype: !!python/name:meerkat.block.manager.BlockManager ''
