_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/140036713353424
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 5995
  slices:
    block:
      block_dir: blocks/140036721952176
      block_index:
        start: 0
        step: null
        stop: 3
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 5995
dtype: !!python/name:meerkat.block.manager.BlockManager ''
