_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139687935238256
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 8923
  id:
    block:
      block_dir: blocks/139689755796672
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 8923
dtype: !!python/name:meerkat.block.manager.BlockManager ''
