_column_order:
- id
- image
- split
columns:
  id:
    block:
      block_dir: blocks/139944181027984
      block_index: id
      mmap: false
    dtype: &id001 !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 202599
  image:
    dtype: !!python/name:meerkat.columns.image_column.ImageColumn ''
    len: 202599
  split:
    block:
      block_dir: blocks/139944181027984
      block_index: split
      mmap: false
    dtype: *id001
    len: 202599
dtype: !!python/name:meerkat.block.manager.BlockManager ''
