high_noise_instances_config:
  dir: high_noise_instances
  instances:
    p_118660:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_120032:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_121123:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_121880:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_122144:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_122493:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_122653:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_72776:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_72793:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
    p_72799:
      knn_num: 5
      pattern_size: 10
      snr: 0.25
low_noise_instances_config:
  dir: low_noise_instances
  instances:
    p_118660:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_120032:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_121123:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_121880:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_122144:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_122493:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_122653:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_72776:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_72793:
      knn_num: 5
      pattern_size: 10
      snr: 4
    p_72799:
      knn_num: 5
      pattern_size: 10
      snr: 4
medium_noise_instances_config:
  dir: medium_noise_instances
  instances:
    p_118660:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_120032:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_121123:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_121880:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_122144:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_122493:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_122653:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_72776:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_72793:
      knn_num: 5
      pattern_size: 10
      snr: 1
    p_72799:
      knn_num: 5
      pattern_size: 10
      snr: 1
original_instances_config:
  dir: original_instances
  instances:
    p_118660:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_120032:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_121123:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_121880:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_122144:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_122493:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_122653:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_72776:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_72793:
      knn_num: 5
      pattern_size: 10
      snr: -1
    p_72799:
      knn_num: 5
      pattern_size: 10
      snr: -1
