_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139895627749264
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 9000
  id:
    block:
      block_dir: blocks/139895622828192
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 9000
dtype: !!python/name:meerkat.block.manager.BlockManager ''
