_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/139690011363552
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 6027
  slices:
    block:
      block_dir: blocks/139690005850912
      block_index:
        start: 0
        step: null
        stop: 3
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 6027
dtype: !!python/name:meerkat.block.manager.BlockManager ''
