_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/139711440394608
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 6088
  slices:
    block:
      block_dir: blocks/139708253924080
      block_index:
        start: 0
        step: null
        stop: 2
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 6088
dtype: !!python/name:meerkat.block.manager.BlockManager ''
