_column_order:
- id
- target
- probs
- split
columns:
  id:
    block:
      block_dir: blocks/139689755860368
      block_index: id
      mmap: false
    dtype: &id001 !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 5965
  probs:
    block:
      block_dir: blocks/139690380990592
      block_index:
        start: 514
        step: 1
        stop: 516
      mmap: false
    dtype: !!python/name:meerkat.ml.prediction_column.ClassificationOutputColumn ''
    len: 5965
  split:
    block:
      block_dir: blocks/139689755860368
      block_index: split
      mmap: false
    dtype: *id001
    len: 5965
  target:
    block:
      block_dir: blocks/139690380991408
      block_index: 0
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 5965
dtype: !!python/name:meerkat.block.manager.BlockManager ''
