_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/139895795768624
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 6031
  slices:
    block:
      block_dir: blocks/139895624659632
      block_index:
        start: 0
        step: null
        stop: 1
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 6031
dtype: !!python/name:meerkat.block.manager.BlockManager ''
