_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/139924292354640
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 6048
  slices:
    block:
      block_dir: blocks/139924451316544
      block_index:
        start: 0
        step: null
        stop: 3
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 6048
dtype: !!python/name:meerkat.block.manager.BlockManager ''
