_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/140493269591088
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 5994
  slices:
    block:
      block_dir: blocks/140496350918160
      block_index:
        start: 0
        step: null
        stop: 1
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 5994
dtype: !!python/name:meerkat.block.manager.BlockManager ''
