_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139690010166944
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 9028
  id:
    block:
      block_dir: blocks/139689468663120
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 9028
dtype: !!python/name:meerkat.block.manager.BlockManager ''
