_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139925083041312
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 8948
  id:
    block:
      block_dir: blocks/139925079084720
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 8948
dtype: !!python/name:meerkat.block.manager.BlockManager ''
