_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/140037328757424
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 8895
  id:
    block:
      block_dir: blocks/140036700789440
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 8895
dtype: !!python/name:meerkat.block.manager.BlockManager ''
