_column_order:
- id
- slices
columns:
  id:
    block:
      block_dir: blocks/139689762560176
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 6107
  slices:
    block:
      block_dir: blocks/139689748608000
      block_index:
        start: 0
        step: null
        stop: 3
      mmap: false
    dtype: !!python/name:meerkat.columns.numpy_column.NumpyArrayColumn ''
    len: 6107
dtype: !!python/name:meerkat.block.manager.BlockManager ''
