_column_order:
- id
- emb
columns:
  emb:
    block:
      block_dir: blocks/139689764262864
      block_index:
        start: 2
        step: 1
        stop: 514
      mmap: false
    dtype: !!python/name:meerkat.columns.tensor_column.TensorColumn ''
    len: 8949
  id:
    block:
      block_dir: blocks/139689749256320
      block_index: id
      mmap: false
    dtype: !!python/name:meerkat.columns.pandas_column.PandasSeriesColumn ''
    len: 8949
dtype: !!python/name:meerkat.block.manager.BlockManager ''
